export const ICON_LEXICON: Record<string, string> = {
  'arrow-up': 'Up',
  'arrow-down': 'Down',
  'arrow-left': 'Previous',
  'arrow-right': 'Next',
  'caret-up': 'Collapse',
  'caret-down': 'Expand',
  'caret-left': 'Previous',
  'caret-right': 'Next',
  'chevron-up': 'Collapse',
  'chevron-down': 'Expand',
  'chevron-left': 'Previous',
  'chevron-right': 'Next',
  'angle-up': 'Collapse',
  'angle-down': 'Expand',
  'angle-left': 'Previous',
  'angle-right': 'Next',
  'double-chevron-up': 'Collapse',
  'double-chevron-down': 'Expand',
  back: 'Back',
  forward: 'Forward',
  'external-link': 'Open External Link',
  'open-in-new': 'Open In New',
  link: 'Link',
  unlink: 'Unlink',
  search: 'Search',
  close: 'Close',
  times: 'Close',
  cross: 'Close',
  cancel: 'Cancel',
  dismiss: 'Dismiss',
  plus: 'Add',
  add: 'Add',
  minus: 'Remove',
  remove: 'Remove',
  delete: 'Delete',
  trash: 'Delete',
  edit: 'Edit',
  pencil: 'Edit',
  save: 'Save',
  disk: 'Save',
  copy: 'Copy',
  duplicate: 'Duplicate',
  paste: 'Paste',
  cut: 'Cut',
  scissors: 'Cut',
  share: 'Share',
  export: 'Export',
  import: 'Import',
  download: 'Download',
  upload: 'Upload',
  print: 'Print',
  printer: 'Print',
  refresh: 'Refresh',
  reload: 'Refresh',
  sync: 'Sync',
  rotate: 'Rotate',
  undo: 'Undo',
  redo: 'Redo',
  send: 'Send',
  'paper-plane': 'Send',
  reply: 'Reply',
  'forward-mail': 'Forward',
  menu: 'Menu',
  hamburger: 'Menu',
  bars: 'Menu',
  grid: 'Grid',
  list: 'List',
  columns: 'Columns',
  rows: 'Rows',
  table: 'Table',
  dashboard: 'Dashboard',
  sidebar: 'Sidebar',
  layout: 'Layout',
  fullscreen: 'Fullscreen',
  maximize: 'Maximize',
  minimize: 'Minimize',
  window: 'Window',
  tab: 'Tab',
  expand: 'Expand',
  collapse: 'Collapse',
  filter: 'Filter',
  funnel: 'Filter',
  sort: 'Sort',
  'sort-asc': 'Sort Ascending',
  'sort-desc': 'Sort Descending',
  'sort-up': 'Sort Ascending',
  'sort-down': 'Sort Descending',
  file: 'File',
  document: 'Document',
  folder: 'Folder',
  'folder-open': 'Open Folder',
  'folder-plus': 'Add Folder',
  archive: 'Archive',
  box: 'Box',
  package: 'Package',
  attachment: 'Attachment',
  paperclip: 'Attachment',
  clipboard: 'Clipboard',
  'clipboard-check': 'Clipboard Check',
  'clipboard-copy': 'Copy To Clipboard',
  'sticky-note': 'Note',
  notebook: 'Notebook',
  book: 'Book',
  play: 'Play',
  pause: 'Pause',
  stop: 'Stop',
  'skip-forward': 'Skip Forward',
  'skip-backward': 'Skip Backward',
  rewind: 'Rewind',
  'fast-forward': 'Fast Forward',
  next: 'Next',
  previous: 'Previous',
  shuffle: 'Shuffle',
  repeat: 'Repeat',
  volume: 'Volume',
  'volume-up': 'Volume Up',
  'volume-down': 'Volume Down',
  'volume-mute': 'Mute',
  mute: 'Mute',
  microphone: 'Microphone',
  mic: 'Microphone',
  camera: 'Camera',
  video: 'Video',
  image: 'Image',
  picture: 'Image',
  photo: 'Photo',
  gallery: 'Gallery',
  film: 'Film',
  user: 'User',
  person: 'User',
  profile: 'Profile',
  account: 'Account',
  avatar: 'Avatar',
  users: 'Users',
  people: 'People',
  team: 'Team',
  group: 'Group',
  contact: 'Contact',
  'id-card': 'Identity Card',
  badge: 'Badge',
  signin: 'Sign In',
  signout: 'Sign Out',
  'sign-in': 'Sign In',
  'sign-out': 'Sign Out',
  login: 'Log In',
  logout: 'Log Out',
  'login-round': 'Log In',
  key: 'Key',
  password: 'Password',
  fingerprint: 'Fingerprint',
  'face-id': 'Face Id',
  unlock: 'Unlock',
  mail: 'Mail',
  email: 'Email',
  envelope: 'Mail',
  inbox: 'Inbox',
  outbox: 'Outbox',
  message: 'Message',
  chat: 'Chat',
  comment: 'Comment',
  comments: 'Comments',
  'speech-bubble': 'Message',
  phone: 'Phone',
  'phone-call': 'Call',
  call: 'Call',
  telephone: 'Telephone',
  bell: 'Notifications',
  notification: 'Notification',
  alarm: 'Alarm',
  alert: 'Alert',
  rss: 'Rss',
  check: 'Check',
  tick: 'Check',
  ok: 'Ok',
  done: 'Done',
  success: 'Success',
  warning: 'Warning',
  error: 'Error',
  info: 'Info',
  question: 'Question',
  help: 'Help',
  exclamation: 'Exclamation',
  'circle-check': 'Success',
  'circle-x': 'Close',
  'circle-info': 'Info',
  'circle-exclamation': 'Warning',
  star: 'Star',
  'star-empty': 'Star',
  'star-full': 'Star',
  heart: 'Favorite',
  favorite: 'Favorite',
  'thumbs-up': 'Like',
  'thumbs-down': 'Dislike',
  like: 'Like',
  dislike: 'Dislike',
  smile: 'Smile',
  sad: 'Sad',
  mood: 'Mood',
  home: 'Home',
  house: 'Home',
  map: 'Map',
  pin: 'Pin',
  location: 'Location',
  globe: 'Globe',
  world: 'World',
  earth: 'Earth',
  compass: 'Compass',
  navigation: 'Navigation',
  route: 'Route',
  waypoint: 'Waypoint',
  'shopping-cart': 'Shopping Cart',
  cart: 'Cart',
  basket: 'Basket',
  bag: 'Bag',
  gift: 'Gift',
  'credit-card': 'Credit Card',
  wallet: 'Wallet',
  money: 'Money',
  dollar: 'Dollar',
  euro: 'Euro',
  pound: 'Pound',
  yen: 'Yen',
  rupee: 'Rupee',
  bank: 'Bank',
  receipt: 'Receipt',
  invoice: 'Invoice',
  coin: 'Coin',
  'price-tag': 'Price Tag',
  tag: 'Tag',
  label: 'Label',
  barcode: 'Barcode',
  'qr-code': 'Qr Code',
  scan: 'Scan',
  cog: 'Settings',
  gear: 'Settings',
  settings: 'Settings',
  tools: 'Tools',
  wrench: 'Wrench',
  hammer: 'Hammer',
  screwdriver: 'Screwdriver',
  adjustments: 'Adjustments',
  sliders: 'Sliders',
  toggle: 'Toggle',
  switch: 'Switch',
  'chart-bar': 'Bar Chart',
  'chart-pie': 'Pie Chart',
  'chart-line': 'Line Chart',
  analytics: 'Analytics',
  'trending-up': 'Trending Up',
  'trending-down': 'Trending Down',
  graph: 'Graph',
  database: 'Database',
  server: 'Server',
  cpu: 'Cpu',
  memory: 'Memory',
  'hard-drive': 'Hard Drive',
  storage: 'Storage',
  sun: 'Sun',
  moon: 'Moon',
  sunrise: 'Sunrise',
  sunset: 'Sunset',
  cloud: 'Cloud',
  'cloud-rain': 'Rain',
  snowflake: 'Snowflake',
  umbrella: 'Umbrella',
  droplet: 'Droplet',
  water: 'Water',
  fire: 'Fire',
  flame: 'Fire',
  leaf: 'Leaf',
  tree: 'Tree',
  plant: 'Plant',
  flower: 'Flower',
  shield: 'Shield',
  'shield-check': 'Shield Check',
  'shield-exclamation': 'Shield Warning',
  lock: 'Lock',
  'lock-open': 'Unlock',
  safe: 'Safe',
  eye: 'Show',
  'eye-slash': 'Hide',
  'eye-off': 'Hide',
  visible: 'Show',
  hidden: 'Hide',
  show: 'Show',
  hide: 'Hide',
  calendar: 'Calendar',
  clock: 'Clock',
  watch: 'Watch',
  timer: 'Timer',
  stopwatch: 'Stopwatch',
  hourglass: 'Hourglass',
  schedule: 'Schedule',
  history: 'History',
  bookmark: 'Bookmark',
  flag: 'Flag',
  'flag-filled': 'Flag',
  crown: 'Crown',
  trophy: 'Trophy',
  award: 'Award',
  medal: 'Medal',
  'gift-box': 'Gift',
  ticket: 'Ticket',
  code: 'Code',
  terminal: 'Terminal',
  bug: 'Bug',
  qr: 'Qr Code',
};
