#!/bin/bash
# scripts/bump-version.sh [--auto|major|minor|patch|X.Y.Z] [--no-commit]
#
# Bumps version across manifest.json + all package.json files,
# prepends a CHANGELOG.md entry from commits since the last v* tag,
# then commits + tags (unless --no-commit is passed).
#
# --auto (default): conventional-commits driven
#   any 'BREAKING' or '!:'  -> major
#   any 'feat:' or 'feat(…)' -> minor (unless already major)
#   everything else          -> patch
#
# Exit codes:
#   0  success
#   1  error (malformed semver, write failure, etc.)
#  42  nothing to bump (no commits since last tag)
#
# The auto-bumped commit + tag use the GitHub noreply email of manishjnv
# (matches the email-privacy block on the live.com account) unless
# GIT_COMMITTER_EMAIL / AUTHOR env vars are set.

set -euo pipefail

MODE="--auto"
NO_COMMIT=false
for arg in "$@"; do
  case "$arg" in
    --no-commit) NO_COMMIT=true ;;
    --*)         MODE="$arg" ;;
    *)           MODE="$arg" ;;
  esac
done
MODE="${MODE#--}"

MANIFEST="packages/extension/manifest.json"
PACKAGE_JSONS=(
  "package.json"
  "packages/core/package.json"
  "packages/ai-engine/package.json"
  "packages/extension/package.json"
)
CHANGELOG="CHANGELOG.md"

[[ -f "$MANIFEST" ]] || { echo "ERR: $MANIFEST not found"; exit 1; }

CURRENT=$(node -p "require('./$MANIFEST').version")

LAST_TAG=$(git tag --list 'v*' --sort=-v:refname | head -1 || true)

if [[ "$MODE" == "auto" ]]; then
  if [[ -n "$LAST_TAG" ]]; then
    COMMITS=$(git log --format='%s' "$LAST_TAG..HEAD")
    RANGE="$LAST_TAG..HEAD"
  else
    # First run — bootstrap: include last 20 commits so changelog has content.
    COMMITS=$(git log --format='%s' -20 HEAD)
    RANGE="HEAD~20..HEAD"
  fi

  if [[ -z "${COMMITS// /}" ]]; then
    echo "No commits since ${LAST_TAG:-repo start} — nothing to bump."
    exit 42
  fi

  BUMP="patch"
  while IFS= read -r msg; do
    [[ -z "$msg" ]] && continue
    if [[ "$msg" == BREAKING* ]] || [[ "$msg" == *'!:'* ]]; then
      BUMP="major"
      break
    elif [[ "$msg" == feat:* ]] || [[ "$msg" == feat\(*\):* ]]; then
      [[ "$BUMP" == "patch" ]] && BUMP="minor"
    fi
  done <<< "$COMMITS"
  MODE="$BUMP"
else
  if [[ -n "$LAST_TAG" ]]; then
    RANGE="$LAST_TAG..HEAD"
  else
    RANGE="HEAD~20..HEAD"
  fi
fi

IFS='.' read -r MAJ MIN PAT <<< "$CURRENT"

case "$MODE" in
  major) NEW="$((MAJ+1)).0.0" ;;
  minor) NEW="$MAJ.$((MIN+1)).0" ;;
  patch) NEW="$MAJ.$MIN.$((PAT+1))" ;;
  *)
    if [[ "$MODE" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
      NEW="$MODE"
    else
      echo "ERR: unknown mode '$MODE' (expected auto|major|minor|patch|X.Y.Z)"
      exit 1
    fi
    ;;
esac

if [[ "$NEW" == "$CURRENT" ]]; then
  echo "Version unchanged ($CURRENT → $NEW). Nothing to do."
  exit 42
fi

echo "Bumping $CURRENT → $NEW (mode=$MODE)"

# Update manifest.json
NEW="$NEW" node -e "
const fs = require('fs');
const p = require('path').resolve(process.argv[1]);
const m = JSON.parse(fs.readFileSync(p, 'utf8'));
m.version = process.env.NEW;
fs.writeFileSync(p, JSON.stringify(m, null, 2) + '\n');
" "$MANIFEST"

# Sync all package.json siblings
for pkg in "${PACKAGE_JSONS[@]}"; do
  [[ -f "$pkg" ]] || continue
  NEW="$NEW" node -e "
  const fs = require('fs');
  const p = require('path').resolve(process.argv[1]);
  const pj = JSON.parse(fs.readFileSync(p, 'utf8'));
  pj.version = process.env.NEW;
  fs.writeFileSync(p, JSON.stringify(pj, null, 2) + '\n');
  " "$pkg"
done

# Group commits by conventional-commit type for the CHANGELOG entry
DATE=$(date +%Y-%m-%d)

FEATS=$(git log --format='- %s' "$RANGE" 2>/dev/null | grep -E '^- feat' || true)
FIXES=$(git log --format='- %s' "$RANGE" 2>/dev/null | grep -E '^- fix' || true)
OTHERS=$(git log --format='- %s' "$RANGE" 2>/dev/null | grep -vE '^- (feat|fix)' || true)

ENTRY_FILE=$(mktemp)
{
  printf "## v%s — %s\n" "$NEW" "$DATE"
  if [[ -n "$FEATS" ]]; then
    printf "\n### Added\n\n%s\n" "$FEATS"
  fi
  if [[ -n "$FIXES" ]]; then
    printf "\n### Fixed\n\n%s\n" "$FIXES"
  fi
  if [[ -n "$OTHERS" ]]; then
    printf "\n### Other\n\n%s\n" "$OTHERS"
  fi
  printf "\n"
} > "$ENTRY_FILE"

if [[ ! -f "$CHANGELOG" ]]; then
  {
    printf "# AccessBridge Changelog\n\n"
    printf "Auto-generated by \`scripts/bump-version.sh\` on every release.\n"
    printf "Newest entry on top; \`%s\` also serves this file as \`/api/version\` changelog.\n\n" "/api"
    cat "$ENTRY_FILE"
  } > "$CHANGELOG"
else
  TMP=$(mktemp)
  # Preserve the 4-line header, insert new entry right after
  head -n 4 "$CHANGELOG" > "$TMP"
  cat "$ENTRY_FILE" >> "$TMP"
  tail -n +5 "$CHANGELOG" >> "$TMP"
  mv "$TMP" "$CHANGELOG"
fi

rm -f "$ENTRY_FILE"

echo "✓ Updated $MANIFEST, ${#PACKAGE_JSONS[@]} package.json files, $CHANGELOG"

if [[ "$NO_COMMIT" == "true" ]]; then
  echo "--no-commit: leaving changes unstaged for review."
  exit 0
fi

git add "$MANIFEST" "${PACKAGE_JSONS[@]}" "$CHANGELOG"

# Export so BOTH git commit and git tag -a see the noreply identity.
# GitHub rejects pushes whose author OR committer OR tagger email is
# live.com (manishjnv account enforces email-privacy). Annotated tags
# take their tagger from GIT_COMMITTER_* — setting only --author on
# git commit is insufficient.
export GIT_COMMITTER_EMAIL="${GIT_COMMITTER_EMAIL:-257227540+manishjnv@users.noreply.github.com}"
export GIT_COMMITTER_NAME="${GIT_COMMITTER_NAME:-Manish Kumar}"

git commit \
  --author="${AUTHOR:-Manish Kumar <257227540+manishjnv@users.noreply.github.com>}" \
  -m "chore(release): v$NEW

Auto-generated by scripts/bump-version.sh ($MODE bump from v$CURRENT).
See CHANGELOG.md for the full v$NEW entry."

git tag -a "v$NEW" -m "v$NEW — auto-bumped $MODE from v$CURRENT"

echo "✓ Committed + tagged v$NEW"
